### ISSUE TITLE
Create A Section About Different Programming Paradigms

### ISSUE THREAD

**Issue by AlaminMahamud** [me-shaon/bangla-programming-resources#1]
As we all know programming language are sorts of tools. so different kind of tools are used for different kinds of scenarios. 

There are lots of programming paradigms like functional, OOP having a basic understanding of why they are is essential in my opinion.

**Comment by me-shaon** [comment]
Could you please suggest some 'bangla' articles or resources related about different programming paradigms? I'll update the repo with them. Thanks for the suggestion.

**Comment by AlaminMahamud** [comment]
i think i have some links. if possible i will write some

**Comment by me-shaon** [comment]
will definitely appreciate you contribution.
