### ISSUE TITLE
Link for হ্যাশটেবিল (Hashtable) - আলাভোলা is not working

### ISSUE THREAD

**Issue by princesust** [me-shaon/bangla-programming-resources#18]
http://ami-alavola.rhcloud.com/?p=198
Basically most of the links by " আলাভোলা " is not working

**Comment by me-shaon** [comment]
I heard that he won't maintain his blog anymore. But he started posting his previously written articles in 'প্রোগ্রামিং পাতা' Medium publication. I'll update the links as soon as he updates them.
