### ISSUE TITLE
OAUTH- (ওঅথ) অথেনটিকেশন কি , কিভাবে কাজ করে ? - Link not working 

### ISSUE THREAD

**Issue by kaiser-tushar** [me-shaon/bangla-programming-resources#20]
Maybe [Site url ](http://backdoorweb.com/oauth-%E0%A6%93%E0%A6%85%E0%A6%A5-%E0%A6%85%E0%A6%A5%E0%A7%87%E0%A6%A8%E0%A6%9F%E0%A6%BF%E0%A6%95%E0%A7%87%E0%A6%B6%E0%A6%A8-%E0%A6%95%E0%A6%BF-%E0%A6%95%E0%A6%BF%E0%A6%AD%E0%A6%BE%E0%A6%AC%E0%A7%87/) has been changed

**Comment by me-shaon** [comment]
The site seems suspended. So, I'm going to remove the link from this repo. Thanks for noticing.
