### ISSUE TITLE
সোজা বাংলায় ৩ মিনিটে OAuth! - অনিরুদ্ধ অধিকারী - Link not working

### ISSUE THREAD

**Issue by kaiser-tushar** [me-shaon/bangla-programming-resources#21]
May be [Site URL](http://www.adhikary.net/post/oauth-bengali/) has been changed

**Comment by me-shaon** [comment]
I've knocked the owner of the site and waiting for his reply. Thanks for noticing. :)

**Comment by me-shaon** [comment]
The author didn't reply and the link is not available anymore. So, I'm going to remove this link from the resources list.
