### ISSUE TITLE
Dynamic Programming Optimization - Convex Hull Trick

### ISSUE THREAD

**Issue by mdzobayer** [me-shaon/bangla-programming-resources#22]
https://rezwanarefin01.github.io/posts/convex-hull-trick/

**Comment by me-shaon** [comment]
Could you please make a Pull Request by adding this link to the appropriate category?

**Comment by mdzobayer** [comment]
i am new on github. I can't make a pull request. That's why i comment the link.

**Comment by me-shaon** [comment]
Added. Thanks.
