### ISSUE TITLE
Can the links be copied?

### ISSUE THREAD

**Issue by rng70** [me-shaon/bangla-programming-resources#44]
Can I copy the links from you repo to my repo instead of forking it? I was trying to make a resource repo with pretty much all topics and blogs not only in bengali but also for other language. and in a section I want to copy the links. Can I do that? I will provide the links of you repo as a credit of yours.

**Comment by t2222** [comment]
Dear Al Arafat Tanin,
Thanks for your email. The links that you mentioned are not mine. I forked
it from https://github.com/me-shaon/bangla-programming-resources . If you
want to give credit, give it to this guy.
With regards,
Tousif

**Comment by rng70** [comment]
Yeah .. it was my bad actually. I will give that guy the credit and obviously he deserves . Thank you for your reply.
